name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        os:
         - win-x64
         - osx-x64
         - linux-x64

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - shell: cmd
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd PlayerConstDumper
        dotnet nuget add source --username Lord-Giganticus --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Lord-Giganticus/index.json"
        dotnet restore
        dotnet build -p:Configuration=Release
        pushd %CD%
        cd bin\Release\net6.0
        mkdir publish
        set out=%CD%\publish
        set rid=${{ matrix.os }}
        popd
        dotnet publish -c Release -r %rid% --self-contained true -p:PublishSingleFile=true -o %out%\%rid%
        pushd %CD%
        cd %out%\%rid%
        rm *.pdb
        cp PlayerConstDumper* ${{ github.workspace }}\build
    - uses: actions/upload-artifact@v2.3.1
      with:
        name: ${{ matrix.os }}
        path: ${{ github.workspace }}/build
  publish:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: windows-latest

    steps:
     - uses: actions/checkout@v2
     - shell: cmd
       run: |
          cd ${{ github.workspace }}
          mkdir build
          pushd %CD%
          cd build
          mkdir win-x64
          mkdir linux-x64
          mkdir osx-x64
          popd
     - uses: actions/download-artifact@v2.1.0
       with:
        name: win-x64
        path: ${{ github.workspace }}/build/win-x64
     - uses: actions/download-artifact@v2.1.0
       with:
        name: linux-x64
        path: ${{ github.workspace }}/build/linux-x64  
     - uses: actions/download-artifact@v2.1.0
       with:
        name: osx-x64
        path: ${{ github.workspace }}/build/osx-x64  
     - shell: cmd
       run: |
          pushd ${{ github.workspace }}
          cd build
          7z a "${{ github.workspace}}/PlayerConstDumper.zip" osx-x64 linux-x64 win-x64
          popd
     - uses: "marvinpinto/action-automatic-releases@latest"
       with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Auto"
        prerelease: true
        title: "Auto Build"
        files: |
          *.zip
